{% set name = "openalea.deploy" %}
{% set version = "2.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
    - pywin32 # [win]
    - six
  run:
    - python
    - setuptools
    - pywin32 # [win]
    - six
    - path.py

test:
  imports:
    - openalea.deploy

about:
  home: http://github.com/openalea/deploy
  license: CECILL-C
  license_file: LICENSE
  summary: OpenAlea.Deploy support the installation of OpenAlea packages via the network and manage their dependencies.
